const ContactData = [
  {
    name: `""><img srcx onerror=prompt(/xss/);><""`,
    company: `tested12's Company`,
    title: '-',
    email: 'zealmaker1@gmail.com',
    owner: 'David Da Silva',
    street: '-',
    dateCreated: '10/19/2021',
    lastContact: '4/28/2022',
    initials: 'IO',
    phone: '412412421421'
  },
  {
    name: `"-alert(document.domain)-"`,
    company: 'Maillak',
    title: '-',
    email: 'wosovip821@maillak.com',
    owner: 'David Da Silva',
    street: '-',
    dateCreated: '10/19/2021',
    lastContact: '-',
    initials: 'A',
    phone: '-'
  },
  {
    name: `The Soapman' Soapman`,
    company: `The Soapman's Company`,
    title: '-',
    email: 'reginald@hmcgroupllc.com',
    owner: '-',
    street: '-',
    dateCreated: '8/11/2016',
    lastContact: '8/16/2018',
    initials: 'TS',
    phone: '-'
  },
  {
    name: '#TNM Member Services',
    company: 'Tnmwordup',
    title: '-',
    email: 'memberservices@tnmwordup.com',
    owner: 'Marketo Integration',
    street: '-',
    dateCreated: '4/6/2018',
    lastContact: '-',
    initials: 'TS',
    phone: '-'
  },
  {
    name: `&#39;Yulia Myshkovska&#39;`,
    company: 'Cloudastructure',
    title: '-',
    email: 'juliia@cloudastructure.com',
    owner: 'Kristi Lindstrom',
    street: '-',
    dateCreated: '12/30/2020',
    lastContact: '-',
    initials: 'YM',
    phone: '-'
  },
  {
    name: `&lt;liz@airbornedronesco&gt;`,
    company: 'Airborne Drones',
    title: '-',
    email: 'liz@airbornedrones.co',
    owner: '-',
    street: '-',
    dateCreated: '2/5/2021',
    lastContact: '2/15/2021',
    initials: 'L',
    phone: '-'
  },
  {
    name: 'Ale Bar Av',
    company: 'Cantera',
    title: '-',
    email: 'ale@cantera.co',
    owner: '-',
    street: '-',
    dateCreated: '5/30/2018',
    lastContact: '-',
    initials: 'AA',
    phone: '-'
  },
  {
    name: 'Armandeep Singh',
    company: 'Arrow PC Network Pvt. ltd.',
    title: '-',
    email: 'aman@arrowpc.co.in',
    owner: '-',
    street: '-',
    dateCreated: '9/26/2016',
    lastContact: '8/16/2018',
    initials: 'AS',
    phone: '-'
  },
  {
    name: 'Amit Kumar Mandal',
    company: 'Cleartax',
    title: '-',
    email: 'amit.mandal@cleartax.in',
    owner: 'Anya Gayvoronskaya',
    street: '-',
    dateCreated: '8/23/2017',
    lastContact: '6/3/2019',
    initials: 'AS',
    phone: '-'
  },
  {
    name: 'Andreas Semmler',
    company: 'Werkmeister & Company GmbH',
    title: '-',
    email: 'andreas.semmler@werkco.de',
    owner: 'Self Serve',
    street: '-',
    dateCreated: '6/20/2018',
    lastContact: '7/11/2018',
    initials: 'AS',
    phone: '-'
  },
  {
    name: 'Anita Lam',
    company: 'Beyond Media Group',
    title: '-',
    email: 'alam@bmgww.com',
    owner: '-',
    street: '-',
    dateCreated: '6/28/2016',
    lastContact: '-',
    initials: 'AL',
    phone: '-'
  },
  {
    name: 'Annika DiMeo',
    company: 'Brand+Aid',
    title: 'Chief of Staff',
    email: 'annika@brandaiding.com',
    owner: 'Colin Nee',
    street: '-',
    dateCreated: '7/17/2020',
    lastContact: '9/23/2020',
    initials: 'AD',
    phone: '-'
  },
  {
    name: 'Azam Ameer',
    company: 'Dream Design Property',
    title: '-',
    email: 'azam.a@ddpproperty.com.au',
    owner: '-',
    street: '-',
    dateCreated: '2/8/2016',
    lastContact: '-',
    initials: 'AA',
    phone: '-'
  },
  {
    name: 'Barb Merill',
    company: 'Flathead Valley Brokers',
    title: '-',
    email: 'barb@fvbmt.com',
    owner: 'Nikolas Khachiyan',
    street: '-',
    dateCreated: '5/22/2019',
    lastContact: '5/22/2019',
    initials: 'BM',
    phone: '-'
  },
  {
    name: 'Brittany George',
    company: 'Midwest Engineering',
    title: '-',
    email: 'test@testing.com',
    owner: '-',
    street: '1234 Main St',
    dateCreated: '5/4/2015',
    lastContact: '1/18/2016',
    initials: 'BG',
    phone: '-'
  },
]

export default ContactData